name: Build
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3

      - name: Install python
        run: yum install -y python

      - name: Install python dependencies
        run: pip install meson ninja

      - name: Install g++
        run: yum install -y g++

      - name: Install cmake
        run: yum install -y cmake

      - name: Meson setup
        run: meson setup builddir

      - name: Run build
        run: meson compile -v -C builddir

      - name: Run test
        run: ./builddir/run_test

